#ifndef CHANNEL_CARD_H
#define CHANNEL_CARD_H

namespace BELOTE {

enum CARD
{
    SPADES_SEVEN,
    SPADES_HEIGHT,
    SPADES_NINE,
    SPADES_TEN,
    SPADES_JACK,
    SPADES_QUEEN,
    SPADES_KING,
    SPADES_ACE,
    HEARTS_SEVEN,
    HEARTS_HEIGHT,
    HEARTS_NINE,
    HEARTS_TEN,
    HEARTS_JACK,
    HEARTS_QUEEN,
    HEARTS_KING,
    HEARTS_ACE,
    CLUBS_SEVEN,
    CLUBS_HEIGHT,
    CLUBS_NINE,
    CLUBS_TEN,
    CLUBS_JACK,
    CLUBS_QUEEN,
    CLUBS_KING,
    CLUB_ACE,
    DIAMONDS_SEVEN,
    DIAMONDS_HEIGHT,
    DIAMONDS_NINE,
    DIAMONDS_TEN,
    DIAMONDS_JACK,
    DIAMONDS_QUEEN,
    DIAMONDS_KING,
    DIAMONDS_ACE
};

}

#endif // CHANNEL_CARD_H
