
node:
  image: pandirc/dev
  command: sh -c 'nodemon --exec babel-node ./src/server.js DEV'
  hostname: node
  volumes:
   - ./..:/app
  ports:
   - "8088:8088"
   - "8089:8089"
  links:
   - mongo:mongo
   - redis:redis

mongo:
  image: mongo
  hostname: mongo
  volumes:
   - mongoirc:/data/db

redis:
  image: redis
  hostname: redis