version: "2"
#nodemon --ignore ./src/modules/file --ignore ./__uploaded_files__ --exec babel-node ./src/server.js DEV
#node ./dist/server.js DEV
services:
  node:
    image: pandirc/dev
    command: sh -c 'npm run build'
    entrypoint: node src/nodemon.js
    environment:
    - DEBUG=server:*
    hostname: node
    stop_signal: SIGINT
    volumes:
     - ./..:/app
    ports:
     - "8088:8088"
     - "8089:8089"
    links:
     - mongo:mongo
     - redis:redis
     - fileserver:fileserver

  fileserver:
    image: pandirc/dev
    command: sh -c 'echo "running"'
    entrypoint: nodemon --delay 10000 --watch ./src/modules/file --ignore ./__uploaded_files__ --exec babel-node ./src/modules/file/server.js DEV
    stop_signal: SIGINT
    environment:
    - DEBUG=fileserver
    hostname: fileserver
    volumes:
     - ./..:/app
    ports:
    - "3001:3001"
    - "8090:8090"
    - "8091:8091"
    links:
    - redis:redis

  mongo:
    image: mongo:3.4
    hostname: mongo
    volumes:
     - mongoirc:/data/db

  redis:
    image: redis:3.2
    hostname: redis

volumes:
  mongoirc:
    external:
      name: mongoirc