node:
  image: pandirc/dev
  command: sh -c 'nodemon --debug --ignore ./src/modules/file --exec babel-node ./src/server.js DEV'
  hostname: node
  volumes:
   - ./..:/app
  ports:
   - "8088:8088"
   - "8089:8089"
  links:
   - mongo:mongo
   - redis:redis
   - fileserver:fileserver

fileserver:
  image: pandirc/dev
  command: sh -c 'nodemon --debug --watch ./src/modules/file/* --exec babel-node ./src/modules/file/server.js DEV'
  hostname: fileserver
  volumes:
   - ./..:/app
  ports:
  - "3001:3001"
  - "8090:8090"
  links:
  - redis:redis

mongo:
  image: mongo
  hostname: mongo
  volumes:
   - mongoirc:/data/db

redis:
  image: redis
  hostname: redis