
node_prod:
  image: bitnami/node:7
  command: sh -c 'npm run build && node dist/app.js PROD'
  hostname: node
  volumes:
   - ./..:/app
  ports:
   - "8088:4001"
   - "8089:4000"
   - "3001:3999"
  links:
   - mongo_prod:mongo_prod
   - redis_prod:redis_prod

mongo_prod:
  image: mongo
  hostname: mongo_prod
  volumes:
   - mongoirc_prod:/data/db

redis_prod:
  image: redis
  hostname: redis_prod