
node:
  image: pandirc/runtest
  command: sh -c 'npm run build && node dist/server.js TEST'
  hostname: node
  volumes:
   - ./..:/app
  ports:
   - "8088:8088"
   - "8089:8089"
  links:
   - mongo:mongo
   - redis:redis

mongo:
  image: mongo
  hostname: mongo
  volumes:
   - mongoirc:/data/db

redis:
  image: redis
  hostname: redis