version: "2"

services:
  preload:
    image: pandirc/dev
    entrypoint: npm run build
    volumes:
     - ./..:/app

  node:
    image: pandirc/runtest
    command: npm run build
    #entrypoint: ./docker/script.sh
    entrypoint: node ./dist/app.js TEST
    environment:
      - DEBUG=app:test
    hostname: node
    stop_signal: SIGINT
    volumes:
     - ./..:/app
    ports:
     - "8088:8088"
     - "8089:8089"
    links:
     - mongo:mongo
     - redis:redis
     - fileserver:fileserver
    depends_on:
     - preload

  fileserver:
    image: pandirc/dev
    command: sh -c 'nodemon --watch ./src/lib/file --ignore ./__uploaded_files__ --exec babel-node ./src/lib/file/server.js DEV'
    hostname: fileserver
    volumes:
     - ./..:/app
    ports:
    - "3001:3001"
    - "8090:8090"
    - "8091:8091"
    links:
    - redis:redis
    - preload

  mongo:
    image: mongo:3.4
    hostname: mongo
    volumes:
     - mongoirc:/data/db

  redis:
    image: redis:3.2
    hostname: redis

volumes:
  mongoirc:
    external:
      name: mongoirc